config/routes.rb
Ridiculous::Application.routes.draw do
  root to: 'suppliers#index'
  devise_for :users
  resources :suppliers
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
end

app/models/asset_url.rb
class AssetUrl
  
  def self.url
    if Rails.env.production?
      url = Rails.application.config.action_controller.asset_host + '/'
    else Rails.env.development?
      url = '/'
    end
  end

end

app/models/supplier.rb
#encoding: utf-8
class Supplier < ActiveRecord::Base
  
  has_and_belongs_to_many :tags
  has_many :taggings
  has_many :tags, -> { uniq }, through: :taggings
  
  validates :name, :address, :latitude, :longitude, presence: true
  validates :name, uniqueness: true
  validates :name, :address, :website, length: {maximum: 100}
  validates :phone, length: {maximum: 15} #Longest possible phone number (No minimum in case of network shortcuts)
  validate :validate_url
  validate :google_maps_can_read_address
  validate :within_driving_distance, :if => :geocoded?
  
  geocoded_by :address
  before_validation :clear_latlong
  before_validation :geocode
  
  default_scope { order('suppliers.name') }
  
  #
  # Validation methods
  #
  
  def clear_latlong
    self.latitude = ''
    self.longitude = ''
  end
  
  def google_maps_can_read_address
    if self.latitude.blank? || self.longitude.blank?
      
      #Removes unhelpful error messages "Latitude/Longitude can't be blank"
      errors.delete(:latitude)
      errors.delete(:longitude)
      errors.add :address, "couldn't be read by Google Maps."
    end
  end
  
  def within_driving_distance
    if self.distance_from([Rails.configuration.ridiculous_lat, Rails.configuration.ridiculous_lon]) > 200
      # Allows user to keep address without town name unless the town name is necessary for GMaps to understand
      if self.address.include? 'växjö'
        errors.add :address, "is more than 200 miles away."
      else
        self.address << ' växjö'
        self.geocode
        self.within_driving_distance
      end
    end
  end
  
  def validate_url
    begin
      url = URI.parse self.website
      
      unless right_scheme url
        errors.add :website, "is not a valid link. Did you mean " + url.host + '?'
      end
    rescue URI::InvalidURIError
      errors.add :website, 'is not a valid link.'
    end
  end
  
  # Checks if a link has scheme other than http (for example ftp) 
  # Returns true if there is no scheme (for example google.com)
  def right_scheme url
    url.kind_of?(URI::HTTP) or url.kind_of?(URI::HTTPS) or !url.scheme
  end
  
  #
  # Tagging
  #
  
  def tag_list
    self.tags.pluck(:name).join(", ")
  end
  
  # Deletes all tags from Supplier and replaces with new string
  def tag_list=tag_string
    self.tags = tag_string.split(',').collect{|tag| Tag.find_or_create_by(name: tag.strip)}
  end
  
  #
  # Search
  #
  def self.search(query)
    if query.present?
      includes(:tags)
      .where('suppliers.name ilike ? OR suppliers.address ilike ? OR tags.name ilike ? ', "%#{query}%", "%#{query}%", "%#{query}%")
      .references(:tags)
    else
      all
    end
  end
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :suppliers, through: :taggings
  
  # Fails silently. Reasoning: The only failed input is a duplicate or blank.
  # The user doen't need to be told to delete duplicate or blank from input.
  validates :name, uniqueness: true
  validates :name, presence: true
  
  default_scope { order('name') }
  
  before_save { self.name.downcase! }

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :supplier
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.search(params[:query])
    @paginated_suppliers = @suppliers.page(params[:page]).per(6)
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
    @tag_list = session[:tag_list]
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)
    session[:tag_list]= supplier_params[:tag_list]

    respond_to do |format|
      if @supplier.save
        session[:tag_list] = ''
        format.html { redirect_to root_path, notice: 'Supplier was successfully created.' }
        format.json { render action: 'index', status: :created, location: @supplier }
      else
        @tag_list = session[:tag_list]
        format.html { render action: 'new' }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to root_path, notice: 'Supplier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy    
    respond_to do |format|
      if @supplier.destroy
        format.json { head :no_content }
      else
        format.json { render json: @supplier.errors }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name, :address, :latitude, :longitude, :phone, :website, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def twitterized_type(type)
    case type
      when :alert
        "warning"
      when :danger
        "error"
      when :notice
        "info"
      when :success
        "success"
      else
        type.to_s
    end
  end
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
  def edit_icon id, field
    image_tag(AssetUrl.url + "img/icons/edit.png", 
                    :alt => "edit",
                    :class => "edit_icon",
                    :height => "12px",
                    :width => "22px",
                    :id => field + id.to_s )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ridiculous Hat Supplier Tracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
  <meta name="description" content="Supplier tracking for Ridiculous Hat Fine Foods">
  <meta name="author" content="codinatrix">
  <meta name="robots" content="follow, index">
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Vollkorn:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Slab' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/img/favicon.png' %>
  
  <!--[if lt IE 9]>
	<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js" />
  <![endif]-->
</head>
<body id ="<%= yield :body_id %>">
	
<% flash.each do |type, message| %>
  <div class="alert alert-<%= twitterized_type(type) %>"><button type="button" class="close" data-dismiss="alert">x</button><%= message %></div>
<% end %>

<%= yield %>


</body>
</html>

app/views/suppliers/_form.html.erb
<div class="form_wrap">
<%= form_for @supplier, html: { role: "form" } do |f| %>
<h1>Add a supplier</h1>
  <% if @supplier.errors.any? %>
      <ul>
      <% @supplier.errors.full_messages.each do |msg| %>
        <li class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</button><%= msg %></li>
      <% end %>
      </ul>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, :required => true, :placeholder => 'Supplier name', :maxlength => 100, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.text_field :address, :required => true, :placeholder => 'Address', :maxlength => 100, :class => 'form-control' %>
  </div>
  <div class="form-group">    
    <%= f.telephone_field :phone, :placeholder => 'Phone number', :maxlength => 15, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.text_field :website, :placeholder => 'Website', :maxlength => 100, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.text_field :tag_list, :value => @tag_list, :placeholder => 'Tags (separate with comma)', :maxlength => 100, :class => 'form-control' %>
   
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/suppliers/_supplier.html.erb
<div class= "supplier_card_wrap col-md-4 col-sm-6 col-xs-12" >
	<ul class="supplier_card">
      <li><strong><%= best_in_place supplier, :name, :activator => "#name" + supplier.id.to_s  %></strong>
      	<%= edit_icon supplier.id, 'name' if user_signed_in? %>
      </li>
      <li><%= best_in_place supplier, :address, :activator => "#address" + supplier.id.to_s  %>
      	<%= edit_icon supplier.id, 'address' if user_signed_in? %>
      </li>
      <li><%= best_in_place supplier, :phone, :activator => "#phone" + supplier.id.to_s  %>
      	<%= edit_icon supplier.id, 'phone' if user_signed_in? %>
      </li>
      <li><%= best_in_place supplier, :website, :activator => "#website" + supplier.id.to_s  %>
      	<%= edit_icon supplier.id, 'website' if user_signed_in? %>
      </li>
      <li class="tag_list"><%= best_in_place supplier, :tag_list, :activator => "#tag_list" + supplier.id.to_s  %>
      	<%= edit_icon supplier.id, 'tag_list' if user_signed_in? %>
      </li>
      <li><%= link_to( image_tag(AssetUrl.url + "img/icons/delete.png", 
		                    :alt => "delete",
		                    :class => "delete_icon" ),
		              supplier,
		              remote: true,
		              method: :delete,
		              :data => { :confirm => 'Are you sure you want to delete ' + supplier.name + '?' }) if user_signed_in? %>
      </li>
	</ul>
</div>

app/views/suppliers/index.html.erb
<% content_for :body_id, "home_page" %>

<markers>
<% @suppliers.each do |supplier| %>
	<marker name="<%= supplier.name %>" address="<%= supplier.address %>" lat="<%= supplier.latitude %>" lng="<%= supplier.longitude %>"></marker>
<% end %>
</markers>
<div id="map_canvas"></div>
<div id="you_are_here" data-name="Ridiculous Hat" data-address="<%= Rails.configuration.ridiculous_address %>" data-lat="<%= Rails.configuration.ridiculous_lat %>" data-lng="<%= Rails.configuration.ridiculous_lon %>"></div>
<%= image_tag AssetUrl.url + "img/logo.png", :alt => "logo", :id => "logo" %>  
<nav class="navbar" role="navigation">
  <div class="container-fluid">
  	 <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <%= form_tag suppliers_path, method: :get, :class => 'navbar-form navbar-left', :role => 'search' do %>
	    <%= text_field_tag :query, params[:query], class: 'form-control', :placeholder => 'Search supplier or tag' %>
	    <%= submit_tag "Go", :name => nil, :class => 'btn btn-default' %>
	 <% end %>
      <ul class="nav navbar-nav">
      	<li><%= link_to 'All', suppliers_path %></li>
        <li><%= link_to 'New +', new_supplier_path if user_signed_in? %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
		      <li><p class="navbar-text"><%= current_user.email %></p></li>
		      <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
		      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		    <% else %>
		      <li><%= link_to "Login", new_user_session_path %> </li>
		  <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
 
  <div class="pagination_wrap">
	<%= paginate @paginated_suppliers, :remote => true %>
  </div>
  <div class="row">
    <% @paginated_suppliers.each do |supplier| %>
    	<%= render supplier %>
    <% end %>
  </div>
  
  <div class="pagination_wrap">
	<%= paginate @paginated_suppliers, :remote => true %>
  </div>


</div>

app/views/suppliers/index.js.erb
$('.row').html('<%= escape_javascript render(@paginated_suppliers) %>');
$('.pagination_wrap').html('<%= escape_javascript(paginate(@paginated_suppliers, :remote => true).to_s) %>');
RIDICULOUSHAT.reset_new_page();

app/views/suppliers/new.html.erb
<% content_for :body_id, "new_supplier_page" %>

<%= link_to image_tag(AssetUrl.url + "img/logo.png", :alt => "Home"), suppliers_path, :id => "logo_link" %>

<%= link_to 'Home', suppliers_path, :id => "home_link" %>

<%= render 'form' %>